# data.py - Matematika va Ingliz tili savollar bazasi 

TEST_BAZA = {
    "Matematika": {
        "5": [
            {"q": "48 + 27 = ?", "o": ["65", "75", "85", "95"], "a": "75"},
            {"q": "73 - 29 = ?", "o": ["44", "54", "34", "64"], "a": "44"},
            {"q": "6 * 9 = ?", "o": ["54", "56", "48", "64"], "a": "54"},
            {"q": "84 / 7 = ?", "o": ["10", "11", "12", "13"], "a": "12"},
            {"q": "125 + 38 = ?", "o": ["153", "163", "173", "183"], "a": "163"},
            {"q": "200 - 86 = ?", "o": ["104", "114", "124", "134"], "a": "114"},
            {"q": "14 * 5 = ?", "o": ["60", "65", "70", "75"], "a": "70"},
            {"q": "96 / 8 = ?", "o": ["10", "11", "12", "13"], "a": "12"},
            {"q": "67 + 58 = ?", "o": ["115", "125", "135", "145"], "a": "125"},
            {"q": "150 - 75 = ?", "o": ["65", "75", "85", "95"], "a": "75"},
            {"q": "23 * 4 = ?", "o": ["82", "92", "102", "112"], "a": "92"},
            {"q": "144 / 12 = ?", "o": ["10", "11", "12", "13"], "a": "12"},
            {"q": "56 + 78 - 29 = ?", "o": ["95", "105", "115", "125"], "a": "105"},
            {"q": "90 / 5 + 16 = ?", "o": ["30", "32", "34", "36"], "a": "34"},
            {"q": "7 * (8 + 3) = ?", "o": ["63", "77", "70", "81"], "a": "77"},
            {"q": "(45 - 15) * 2 = ?", "o": ["50", "60", "70", "80"], "a": "60"},
            {"q": "100 - (36 + 24) = ?", "o": ["30", "40", "50", "60"], "a": "40"},
            {"q": "64 / (8 * 2) = ?", "o": ["2", "4", "6", "8"], "a": "4"},
            {"q": "1 * 9 + 27 / 3 = ?", "o": ["30", "36", "27", "18"], "a": "18"},
            {"q": "120 / 6 - 8 = ?", "o": ["10", "12", "14", "16"], "a": "12"},
            {"q": "250 + 75 * 2 = ?", "o": ["350", "400", "300", "325"], "a": "400"},
            {"q": "(60 - 20) * 3 + 10 = ?", "o": ["120", "130", "140", "150"], "a": "130"},
            {"q": "180 / (9 * 2) + 5 = ?", "o": ["10", "15", "20", "25"], "a": "15"},
            {"q": "5 * (12 + 8) - 30 = ?", "o": ["70", "80", "90", "100"], "a": "70"},
            {"q": "(90 - 30) / 3 + 14 = ?", "o": ["24", "30", "34", "40"], "a": "34"},
            {"q": "36 ta qalam 4 o'quvchiga bo'lindi, yana 2 tadan berildi. Nechtadan tegdi?", "o": ["9", "10", "11", "12"], "a": "11"},
            {"q": "5 hafta 3 kun necha kun?", "o": ["35", "36", "37", "38"], "a": "38"},
            {"q": "Sonni 5 ga ko'paytirib, 15 ayirsak 40 chiqadi. Sonni toping.", "o": ["9", "10", "11", "12"], "a": "11"},
            {"q": "240 / 4 * 3 + 20 = ?", "o": ["180", "200", "220", "240"], "a": "200"},
            {"q": "3 ta kitob 54 000 so'm. 1 ta kitob necha pul?", "o": ["16 000", "17 000", "18 000", "19 000"], "a": "18 000"}
        ],
        "6": [
            {"q": "345 + 278 = ?", "o": ["623", "613", "523", "633"], "a": "623"},
            {"q": "900 - 456 = ?", "o": ["444", "454", "544", "446"], "a": "444"},
            {"q": "24 * 15 = ?", "o": ["360", "340", "380", "350"], "a": "360"},
            {"q": "144 / 12 = ?", "o": ["10", "11", "12", "13"], "a": "12"},
            {"q": "3/4 + 1/4 = ?", "o": ["1", "1/2", "3/8", "4/8"], "a": "1"},
            {"q": "5/6 - 1/6 = ?", "o": ["2/3", "4/6", "1/2", "1"], "a": "2/3"},
            {"q": "2 * (15 + 10) = ?", "o": ["50", "40", "60", "45"], "a": "50"},
            {"q": "100 / 4 + 25 = ?", "o": ["50", "45", "55", "60"], "a": "50"},
            {"q": "18 * 5 - 40 = ?", "o": ["50", "40", "60", "45"], "a": "50"},
            {"q": "200 - (75 + 25) = ?", "o": ["100", "125", "150", "75"], "a": "100"},
            {"q": "7/8 + 1/8 = ?", "o": ["1", "3/4", "7/16", "1/4"], "a": "1"},
            {"q": "9/10 - 3/10 = ?", "o": ["0.6", "3/5", "6/10", "Barcha javoblar to'g'ri"], "a": "Barcha javoblar to'g'ri"},
            {"q": "36 / (6 * 2) = ?", "o": ["3", "6", "9", "12"], "a": "3"},
            {"q": "(45 + 15) * 3 = ?", "o": ["180", "150", "120", "210"], "a": "180"},
            {"q": "120 / 5 + 18 = ?", "o": ["42", "38", "40", "44"], "a": "42"},
            {"q": "4 * (25 - 5) = ?", "o": ["80", "100", "60", "75"], "a": "80"},
            {"q": "300 - (120 + 80) = ?", "o": ["100", "150", "200", "50"], "a": "100"},
            {"q": "6 * 7 + 42 / 6 = ?", "o": ["49", "42", "48", "50"], "a": "49"},
            {"q": "1/2 + 3/4 = ?", "o": ["1.25", "1 1/4", "5/4", "Barchasi to'g'ri"], "a": "Barchasi to'g'ri"},
            {"q": "5/6 - 1/3 = ?", "o": ["1/2", "3/6", "0.5", "Barchasi to'g'ri"], "a": "Barchasi to'g'ri"},
            {"q": "(3/5 + 2/5) * 10 = ?", "o": ["10", "5", "1", "20"], "a": "10"},
            {"q": "180 / (3 * 5) + 12 = ?", "o": ["24", "12", "15", "18"], "a": "24"},
            {"q": "7 * (12 + 8) - 50 = ?", "o": ["90", "100", "140", "110"], "a": "90"},
            {"q": "(90 - 30) / (5 * 2) = ?", "o": ["6", "10", "12", "5"], "a": "6"},
            {"q": "2/3 + 1/6 = ?", "o": ["5/6", "3/9", "1/2", "1"], "a": "5/6"},
            {"q": "Sonni 4 ga ko'paytirib, 20 qo'shsak 100 chiqadi. Sonni toping.", "o": ["20", "25", "15", "30"], "a": "20"},
            {"q": "3/4 qismi 24 ga teng bo'lgan sonni toping.", "o": ["32", "18", "24", "36"], "a": "32"},
            {"q": "120 ta daraxtning 1/3 qismi olma, qolganining 1/2 qismi o'rik. Nechta o'rik bor?", "o": ["40", "60", "80", "20"], "a": "40"},
            {"q": "2 ta daftar va 1 ta kitob 14 000 so'm. Daftar 4 000 bo'lsa, kitob qancha?", "o": ["6 000", "10 000", "8 000", "7 000"], "a": "6 000"},
            {"q": "Sonni 5 ga bo'lib, 7 qo'shsak 15 chiqadi. Sonni toping.", "o": ["40", "35", "45", "50"], "a": "40"}
        ],
        "7": [
            {"q": "-7 + 12 = ?", "o": ["3", "5", "-5", "-3"], "a": "5"},
            {"q": "15 - 28 = ?", "o": ["-13", "-15", "13", "15"], "a": "-13"},
            {"q": "-6 * 8 = ?", "o": ["-48", "48", "-14", "14"], "a": "-48"},
            {"q": "72 / (-9) = ?", "o": ["-8", "8", "-6", "6"], "a": "-8"},
            {"q": "(-3)^2 = ?", "o": ["-9", "9", "-6", "6"], "a": "9"},
            {"q": "5^2 - 3^2 = ?", "o": ["16", "25", "9", "8"], "a": "16"},
            {"q": "2 * (-4 + 10) = ?", "o": ["8", "12", "6", "-12"], "a": "12"},
            {"q": "-20 + 4 * 5 = ?", "o": ["0", "-20", "20", "-10"], "a": "0"},
            {"q": "18 / 3 - 10 = ?", "o": ["-4", "-2", "2", "4"], "a": "-4"},
            {"q": "-15 + (8 * 2) = ?", "o": ["1", "-1", "3", "-3"], "a": "1"},
            {"q": "2x + 5 = 15", "o": ["3", "4", "5", "6"], "a": "5"},
            {"q": "3x - 7 = 11", "o": ["4", "5", "6", "7"], "a": "6"},
            {"q": "5x = 45", "o": ["7", "8", "9", "10"], "a": "9"},
            {"q": "x / 4 = 6", "o": ["20", "22", "24", "26"], "a": "24"},
            {"q": "2(x + 3) = 14", "o": ["3", "4", "5", "6"], "a": "4"},
            {"q": "4x - 2 = 2x + 6", "o": ["2", "3", "4", "5"], "a": "4"},
            {"q": "3/5 + 2/3 = ?", "o": ["13/15", "12/15", "19/15", "10/15"], "a": "19/15"},
            {"q": "7/9 - 4/9 = ?", "o": ["1/9", "2/9", "3/9", "4/9"], "a": "3/9"},
            {"q": "(-2)^3 = ?", "o": ["-8", "8", "-6", "6"], "a": "-8"},
            {"q": "4^2 + 3^2 = ?", "o": ["25", "24", "23", "26"], "a": "25"},
            {"q": "3(x - 2) + 4 = 16", "o": ["4", "5", "6", "7"], "a": "6"},
            {"q": "2x + 3x - 5 = 20", "o": ["4", "5", "6", "7"], "a": "5"},
            {"q": "x / 2 + 5 = 11", "o": ["10", "11", "12", "13"], "a": "12"},
            {"q": "4(x - 1) = 2(x + 5)", "o": ["5", "6", "7", "8"], "a": "7"},
            {"q": "1/2 + 3/4 - 1/8 = ?", "o": ["1", "1 1/8", "1 1/4", "1 3/8"], "a": "1 1/8"},
            {"q": "3x + 12 = 45", "o": ["9", "10", "11", "12"], "a": "11"},
            {"q": "To'g'ri to'rtburchak: bo'yi 14, eni undan 6 kam. Perimetri?", "o": ["40", "44", "48", "52"], "a": "44"},
            {"q": "35 o'quvchidan 2/5 qismi qizlar. O'g'il bolalar soni?", "o": ["14", "18", "20", "21"], "a": "21"},
            {"q": "x + 2x + 3x = 60", "o": ["8", "9", "10", "12"], "a": "10"},
            {"q": "Sonni 2 ga ko'paytirib, 10 qo'shsak 50 chiqadi. Sonni toping.", "o": ["15", "18", "20", "25"], "a": "20"}
        ],
        "8": [
            {"q": "-12 + 7 = ?", "o": ["-5", "5", "-19", "19"], "a": "-5"},
            {"q": "3^2 + 4^2 = ?", "o": ["25", "24", "23", "26"], "a": "25"},
            {"q": "sqrt(49) = ?", "o": ["6", "7", "8", "9"], "a": "7"},
            {"q": "5 * (2 + 3)^2 = ?", "o": ["100", "125", "75", "50"], "a": "125"},
            {"q": "2x + 6 = 14", "o": ["3", "4", "5", "6"], "a": "4"},
            {"q": "3x - 9 = 0", "o": ["2", "3", "4", "5"], "a": "3"},
            {"q": "(-3)^3 = ?", "o": ["-27", "27", "-9", "9"], "a": "-27"},
            {"q": "8^2 - 6^2 = ?", "o": ["28", "30", "32", "34"], "a": "28"},
            {"q": "sqrt(64) + 6 = ?", "o": ["12", "13", "14", "16"], "a": "14"},
            {"q": "4x = 20", "o": ["4", "5", "6", "7"], "a": "5"},
            {"q": "x^2 = 49", "o": ["7", "-7", "±7", "14"], "a": "±7"},
            {"q": "x^2 - 9 = 0", "o": ["3", "-3", "±3", "9"], "a": "±3"},
            {"q": "(x + 2)(x + 3) = 0", "o": ["-2, -3", "2, 3", "-2, 3", "2, -3"], "a": "-2, -3"},
            {"q": "(x - 4)^2 = 0", "o": ["2", "4", "-4", "0"], "a": "4"},
            {"q": "x^2 + 5x = 0", "o": ["0, -5", "5, 0", "-5", "5"], "a": "0, -5"},
            {"q": "2x^2 = 18", "o": ["3", "-3", "±3", "9"], "a": "±3"},
            {"q": "sqrt(81) - 5 = ?", "o": ["3", "4", "5", "6"], "a": "4"},
            {"q": "(x + 1)(x - 1) = ?", "o": ["x^2 - 1", "x^2 + 1", "x^2 - x", "x^2 + x"], "a": "x^2 - 1"},
            {"q": "9x^2 = 36", "o": ["2", "-2", "±2", "4"], "a": "±2"},
            {"q": "(x + 5)^2 = 25", "o": ["0", "-10", "0, -10", "5"], "a": "0, -10"},
            {"q": "x^2 - 5x = 0", "o": ["0, 5", "5", "-5", "0"], "a": "0, 5"},
            {"q": "(x - 2)(x + 4) = 0", "o": ["2, -4", "-2, 4", "2, 4", "-2, -4"], "a": "2, -4"},
            {"q": "x^2 - 16 = 0", "o": ["4", "-4", "±4", "8"], "a": "±4"},
            {"q": "3x^2 = 27", "o": ["3", "-3", "±3", "9"], "a": "±3"},
            {"q": "(x + 3)^2 = 9", "o": ["0", "-6", "0, -6", "3"], "a": "0, -6"},
            {"q": "x^2 - 7x = 0", "o": ["0, 7", "7", "-7", "0"], "a": "0, 7"},
            {"q": "(x - 5)(x - 2) = 0", "o": ["5, 2", "-5, -2", "5, -2", "-5, 2"], "a": "5, 2"},
            {"q": "x^2 + 6x + 9 = 0", "o": ["-3", "3", "±3", "0"], "a": "-3"},
            {"q": "x^2 - 1 = 0", "o": ["1", "-1", "±1", "0"], "a": "±1"},
            {"q": "2x^2 - 8 = 0", "o": ["2", "-2", "±2", "4"], "a": "±2"}
        ],
        "9": [
            {"q": "5^2 + 12^2 = ?", "o": ["169", "144", "121", "157"], "a": "169"},
            {"q": "sqrt(121) = ?", "o": ["10", "11", "12", "9"], "a": "11"},
            {"q": "x^2 = 36", "o": ["6", "-6", "±6", "12"], "a": "±6"},
            {"q": "2x + 8 = 0", "o": ["-4", "4", "-2", "2"], "a": "-4"},
            {"q": "(x + 3)(x - 3) = ?", "o": ["x^2 - 9", "x^2 + 9", "x^2 - 6", "x^2 + 6"], "a": "x^2 - 9"},
            {"q": "7^2 - 4^2 = ?", "o": ["33", "35", "45", "21"], "a": "33"},
            {"q": "3x = 15", "o": ["3", "4", "5", "6"], "a": "5"},
            {"q": "sqrt(49 + 16) = ?", "o": ["7", "8", "9", "sqrt(65)"], "a": "sqrt(65)"},
            {"q": "(-5)^2 = ?", "o": ["-25", "25", "-10", "10"], "a": "25"},
            {"q": "x^2 - 25 = 0", "o": ["5", "-5", "±5", "0"], "a": "±5"},
            {"q": "x^2 + 5x + 6 = 0", "o": ["-2, -3", "2, 3", "-1, -6", "1, 6"], "a": "-2, -3"},
            {"q": "x^2 - 4x + 4 = 0", "o": ["2", "-2", "±2", "4"], "a": "2"},
            {"q": "x^2 - 9x = 0", "o": ["0, 9", "9", "-9", "0"], "a": "0, 9"},
            {"q": "x^2 - 1 = 0", "o": ["1", "-1", "±1", "0"], "a": "±1"},
            {"q": "2x^2 = 50", "o": ["5", "-5", "±5", "10"], "a": "±5"},
            {"q": "x^2 + 2x - 8 = 0", "o": ["2, -4", "-2, 4", "1, -8", "-1, 8"], "a": "2, -4"},
            {"q": "D = b^2 - 4ac. a=1, b=4, c=4 bo'lsa, D = ?", "o": ["0", "4", "8", "16"], "a": "0"},
            {"q": "(x + 2)^2 = ?", "o": ["x^2 + 4", "x^2 + 2x + 4", "x^2 + 4x + 4", "x^2 + 2x"], "a": "x^2 + 4x + 4"},
            {"q": "9x^2 = 81", "o": ["3", "-3", "±3", "9"], "a": "±3"},
            {"q": "x^2 - 6x + 9 = 0", "o": ["3", "-3", "±3", "0"], "a": "3"},
            {"q": "x^2 - 7x + 10 = 0", "o": ["2, 5", "-2, -5", "1, 10", "-1, -10"], "a": "2, 5"},
            {"q": "x^2 + x - 6 = 0", "o": ["2, -3", "-2, 3", "1, -6", "-1, 6"], "a": "2, -3"},
            {"q": "3x^2 - 12 = 0", "o": ["2", "-2", "±2", "4"], "a": "±2"},
            {"q": "x^2 - 4x - 5 = 0", "o": ["5, -1", "-5, 1", "1, 5", "-1, -5"], "a": "5, -1"},
            {"q": "(x - 3)(x + 5) = 0", "o": ["3, -5", "-3, 5", "3, 5", "-3, -5"], "a": "3, -5"},
            {"q": "x^2 - 2x - 8 = 0", "o": ["4, -2", "-4, 2", "2, -4", "-2, 4"], "a": "4, -2"},
            {"q": "Arifmetik progressiya: a1 = 3, d = 2. a5 ni toping.", "o": ["9", "11", "13", "15"], "a": "11"},
            {"q": "Geometrik progressiya: a1 = 2, q = 3. a4 ni toping.", "o": ["18", "36", "54", "81"], "a": "54"},
            {"q": "x^2 + 3x + 2 = 0", "o": ["-1, -2", "1, 2", "-1, 2", "1, -2"], "a": "-1, -2"},
            {"q": "x^2 - x - 6 = 0", "o": ["2, -3", "-2, 3", "3, -2", "-1, 6"], "a": "3, -2"}
        ],
        "10": [
            {"q": "x^2 = 64", "o": ["8", "-8", "±8", "16"], "a": "±8"},
            {"q": "sqrt(144) = ?", "o": ["10", "11", "12", "13"], "a": "12"},
            {"q": "(x - 2)(x + 2) = ?", "o": ["x^2 - 4", "x^2 + 4", "x^2 - 2x + 4", "x^2 - 4x"], "a": "x^2 - 4"},
            {"q": "2x + 6 = 0", "o": ["3", "-3", "-6", "6"], "a": "-3"},
            {"q": "5^2 + 12^2 = ?", "o": ["169", "144", "125", "130"], "a": "169"},
            {"q": "x^2 - 9 = 0", "o": ["3", "-3", "±3", "9"], "a": "±3"},
            {"q": "3^x = 27", "o": ["2", "3", "4", "5"], "a": "3"},
            {"q": "(-4)^2 = ?", "o": ["-16", "16", "8", "-8"], "a": "16"},
            {"q": "x^2 - 16 = 0", "o": ["±4", "4", "-4", "16"], "a": "±4"},
            {"q": "2^3 = ?", "o": ["6", "8", "9", "12"], "a": "8"},
            {"q": "x^2 + 5x + 6 = 0", "o": ["-2, -3", "2, 3", "-1, -6", "1, 6"], "a": "-2, -3"},
            {"q": "x^2 - 4x + 4 = 0", "o": ["2", "-2", "±2", "4"], "a": "2"},
            {"q": "D = b^2 - 4ac. a=1, b=2, c=1 bo'lsa, D = ?", "o": ["0", "1", "2", "4"], "a": "0"},
            {"q": "x^2 + x - 6 = 0", "o": ["2, -3", "-2, 3", "1, -6", "-1, 6"], "a": "2, -3"},
            {"q": "an = 2n. a5 = ?", "o": ["8", "10", "12", "14"], "a": "10"},
            {"q": "an = 3n + 1. a4 = ?", "o": ["11", "12", "13", "14"], "a": "13"},
            {"q": "7^2 - 5^2 = ?", "o": ["24", "25", "26", "27"], "a": "24"},
            {"q": "x^2 = 49", "o": ["7", "-7", "±7", "14"], "a": "±7"},
            {"q": "x^2 - 7x + 10 = 0", "o": ["2, 5", "-2, -5", "1, 10", "-1, -10"], "a": "2, 5"},
            {"q": "x^2 - 5x = 0", "o": ["0, 5", "5", "-5", "0"], "a": "0, 5"},
            {"q": "sin(30°) = ?", "o": ["1", "1/2", "sqrt(2)/2", "sqrt(3)/2"], "a": "1/2"},
            {"q": "cos(60°) = ?", "o": ["1/2", "sqrt(3)/2", "1", "0"], "a": "1/2"},
            {"q": "2x^2 = 18", "o": ["±2", "±3", "3", "2"], "a": "±3"},
            {"q": "x^2 - 2x - 8 = 0", "o": ["4, -2", "-4, 2", "2, -4", "-2, 4"], "a": "4, -2"},
            {"q": "f(x) = 2x + 3 bo'lsa, f(2) = ?", "o": ["7", "8", "9", "10"], "a": "7"},
            {"q": "x^2 - 1 = 0", "o": ["±1", "1", "-1", "0"], "a": "±1"},
            {"q": "log10(100) = ?", "o": ["1", "2", "3", "10"], "a": "2"},
            {"q": "x^2 - 3x + 2 = 0", "o": ["1, 2", "-1, -2", "2, -1", "-2, 1"], "a": "1, 2"},
            {"q": "integral 1 dx = ?", "o": ["x + C", "1", "0", "C"], "a": "x + C"},
            {"q": "x + y = 5, x - y = 1 bo'lsa, x = ?", "o": ["2", "3", "4", "5"], "a": "3"}
        ],
        "11": [
            {"q": "Limit x->2 (x^2) = ?", "o": ["2", "4", "6", "8"], "a": "4"},
            {"q": "sqrt(169) = ?", "o": ["11", "12", "13", "14"], "a": "13"},
            {"q": "log10(1000) = ?", "o": ["2", "3", "4", "10"], "a": "3"},
            {"q": "x^2 = 81", "o": ["9", "-9", "±9", "18"], "a": "±9"},
            {"q": "f(x) = 3x bo'lsa, f(4) = ?", "o": ["7", "10", "12", "16"], "a": "12"},
            {"q": "7^2 - 3^2 = ?", "o": ["40", "45", "50", "55"], "a": "40"},
            {"q": "cos(0°) = ?", "o": ["0", "1", "-1", "1/2"], "a": "1"},
            {"q": "x^2 - 4 = 0", "o": ["±2", "2", "-2", "4"], "a": "±2"},
            {"q": "x^2 - 5x + 6 = 0", "o": ["2, 3", "-2, -3", "1, 6", "-1, -6"], "a": "2, 3"},
            {"q": "Limit x->3 (x + 2) = ?", "o": ["4", "5", "6", "7"], "a": "5"},
            {"q": "(x^2)' = ?", "o": ["x", "2x", "x^2", "2"], "a": "2x"},
            {"q": "integral 2x dx = ?", "o": ["x^2", "2x^2", "x^2 + C", "2x + C"], "a": "x^2 + C"},
            {"q": "log2(8) = ?", "o": ["2", "3", "4", "5"], "a": "3"},
            {"q": "sin(30°) = ?", "o": ["1", "1/2", "sqrt(2)/2", "sqrt(3)/2"], "a": "1/2"},
            {"q": "cos(60°) = ?", "o": ["1/2", "1", "0", "sqrt(3)/2"], "a": "1/2"},
            {"q": "3^x = 27", "o": ["2", "3", "4", "5"], "a": "3"},
            {"q": "x^2 + 2x + 1 = 0", "o": ["1", "-1", "±1", "0"], "a": "-1"},
            {"q": "sqrt(49) + sqrt(16) = ?", "o": ["11", "12", "13", "14"], "a": "11"},
            {"q": "x^2 - 9x + 20 = 0", "o": ["4, 5", "-4, -5", "2, 10", "1, 20"], "a": "4, 5"},
            {"q": "integral x dx = ?", "o": ["x", "x^2", "x^2/2 + C", "2x + C"], "a": "x^2/2 + C"},
            {"q": "Vektor a=(2,3) bo'lsa, modulini toping.", "o": ["sqrt(5)", "sqrt(13)", "sqrt(9)", "sqrt(12)"], "a": "sqrt(13)"},
            {"q": "log10(1) = ?", "o": ["0", "1", "10", "-1"], "a": "0"},
            {"q": "Limit x->0 (sin(x)/x) = ?", "o": ["0", "1", "∞", "-1"], "a": "1"},
            {"q": "Hosila toping: (5x^2)'", "o": ["5x", "10x", "2x", "5"], "a": "10x"},
            {"q": "integral 3x^2 dx = ?", "o": ["x^3 + C", "3x^3 + C", "x^2 + C", "6x + C"], "a": "x^3 + C"},
            {"q": "x^2 - 6x + 9 = 0", "o": ["3", "-3", "±3", "0"], "a": "3"},
            {"q": "sin^2(x) + cos^2(x) = ?", "o": ["0", "1", "2", "x"], "a": "1"},
            {"q": "f(x) = sin(x) bo'lsa, f'(0) = ?", "o": ["0", "1", "-1", "1/2"], "a": "1"},
            {"q": "Prizmaning asosi yuzi 10, balandligi 5. Hajmi?", "o": ["15", "50", "25", "100"], "a": "50"},
            {"q": "log2(x) = 4 bo'lsa, x = ?", "o": ["8", "16", "2", "4"], "a": "16"}
        ]
    },
    "Ingliz tili": {
        "5": [
            {"q": "1. 'Library' is a place where we:", "o": ["eat food", "read books", "play football", "sleep"], "a": "read books"},
            {"q": "2. 'Bicycle' is a:", "o": ["transport", "animal", "fruit", "school subject"], "a": "transport"},
            {"q": "3. 'Quiet' means:", "o": ["noisy", "silent", "fast", "big"], "a": "silent"},
            {"q": "4. 'Hungry' means:", "o": ["thirsty", "sleepy", "wanting food", "angry"], "a": "wanting food"},
            {"q": "5. 'Usually' means:", "o": ["always", "sometimes", "never", "often"], "a": "often"},
            {"q": "6. 'Lesson' is:", "o": ["subject in school", "game", "building", "toy"], "a": "subject in school"},
            {"q": "7. 'Early' opposite is:", "o": ["late", "fast", "big", "long"], "a": "late"},
            {"q": "8. 'Rainy' weather means:", "o": ["sunny", "windy", "raining", "snowy"], "a": "raining"},
            {"q": "9. 'Friend' means:", "o": ["enemy", "teacher", "buddy", "stranger"], "a": "buddy"},
            {"q": "10. 'Kitchen' is where we:", "o": ["sleep", "cook food", "study", "play"], "a": "cook food"},
            {"q": "11. She ___ very hard every day.", "o": ["study", "studies", "studying", "studied"], "a": "studies"},
            {"q": "12. I ___ my homework yesterday.", "o": ["do", "does", "did", "done"], "a": "did"},
            {"q": "13. They ___ to school now.", "o": ["go", "goes", "are going", "went"], "a": "are going"},
            {"q": "14. He ___ football last Sunday.", "o": ["play", "played", "plays", "playing"], "a": "played"},
            {"q": "15. We ___ not go to school on Sundays.", "o": ["do", "does", "are", "is"], "a": "do"},
            {"q": "16. ___ you like pizza?", "o": ["Do", "Does", "Are", "Is"], "a": "Do"},
            {"q": "17. There ___ a book on the table.", "o": ["am", "is", "are", "be"], "a": "is"},
            {"q": "18. I ___ a student.", "o": ["am", "is", "are", "be"], "a": "am"},
            {"q": "19. She ___ got a cat.", "o": ["have", "has", "is", "are"], "a": "has"},
            {"q": "20. ___ I come in?", "o": ["Must", "Can", "Am", "Is"], "a": "Can"},
            {"q": "21. Identify the noun: 'The boy is running.'", "o": ["boy", "is", "running", "fast"], "a": "boy"},
            {"q": "22. Identify the verb: 'We eat apples.'", "o": ["We", "eat", "apples", "red"], "a": "eat"},
            {"q": "23. Plural of 'Apple':", "o": ["Apples", "Appless", "Applies", "Applees"], "a": "Apples"},
            {"q": "24. Opposite of 'Big':", "o": ["Small", "Large", "Tall", "Short"], "a": "Small"},
            {"q": "25. Identify the adjective: 'The blue sky.'", "o": ["blue", "sky", "the", "is"], "a": "blue"},
            {"q": "26. 'I have a car.' - Which is the object?", "o": ["I", "have", "car", "a"], "a": "car"},
            {"q": "27. Correct sentence:", "o": ["I am happy.", "I is happy.", "I are happy.", "I be happy."], "a": "I am happy."},
            {"q": "28. Negative of 'She likes milk.':", "o": ["She doesn't like milk.", "She not like milk.", "She don't like milk.", "She isn't like milk."], "a": "She doesn't like milk."},
            {"q": "29. Question: 'They are friends.':", "o": ["Are they friends?", "Do they friends?", "Is they friends?", "They are friends?"], "a": "Are they friends?"},
            {"q": "30. Identify the pronoun: 'He is my friend.'", "o": ["He", "is", "my", "friend"], "a": "He"}
        ],
        "6": [
            {"q": "1. She ___ to music every evening.", "o": ["listen", "listens", "listening", "listened"], "a": "listens"},
            {"q": "2. They ___ at the moment.", "o": ["work", "works", "are working", "worked"], "a": "are working"},
            {"q": "3. I ___ to the cinema last night.", "o": ["go", "goes", "went", "gone"], "a": "went"},
            {"q": "4. ___ you ever been to London?", "o": ["Do", "Does", "Have", "Has"], "a": "Have"},
            {"q": "5. He ___ his car tomorrow.", "o": ["wash", "washes", "will wash", "washed"], "a": "will wash"},
            {"q": "6. We ___ since morning.", "o": ["study", "are studying", "have been studying", "studied"], "a": "have been studying"},
            {"q": "7. Look! The sun ___.", "o": ["shine", "shines", "is shining", "shone"], "a": "is shining"},
            {"q": "8. While I ___, the phone rang.", "o": ["read", "am reading", "was reading", "reads"], "a": "was reading"},
            {"q": "9. If it ___, we will stay at home.", "o": ["rain", "rains", "raining", "rained"], "a": "rains"},
            {"q": "10. I ___ my keys.", "o": ["lost", "have lost", "lose", "losing"], "a": "have lost"},
            {"q": "11. This is ___ book in the library.", "o": ["the best", "good", "better", "best"], "a": "the best"},
            {"q": "12. She is ___ than her sister.", "o": ["tall", "taller", "the tallest", "more tall"], "a": "taller"},
            {"q": "13. It is ___ day of the year.", "o": ["hot", "hotter", "the hottest", "more hot"], "a": "the hottest"},
            {"q": "14. English is ___ than Maths.", "o": ["easy", "easier", "the easiest", "more easy"], "a": "easier"},
            {"q": "15. He is ___ boy in the class.", "o": ["the most intelligent", "intelligent", "more intelligent", "intelligentest"], "a": "the most intelligent"},
            {"q": "16. My car is ___ than yours.", "o": ["expensive", "more expensive", "the most expensive", "expensiver"], "a": "more expensive"},
            {"q": "17. Today is ___ than yesterday.", "o": ["cold", "colder", "the coldest", "more cold"], "a": "colder"},
            {"q": "18. She is ___ student in the school.", "o": ["good", "better", "the best", "best"], "a": "the best"},
            {"q": "19. This mountain is ___ than that one.", "o": ["high", "higher", "the highest", "more high"], "a": "higher"},
            {"q": "20. It was ___ film I've ever seen.", "o": ["exciting", "more exciting", "the most exciting", "excitingest"], "a": "the most exciting"},
            {"q": "21. Subject: 'The teacher is explaining.'", "o": ["The teacher", "is", "explaining", "teacher"], "a": "The teacher"},
            {"q": "22. Object: 'I bought a new phone.'", "o": ["I", "bought", "phone", "new"], "a": "phone"},
            {"q": "23. Adverb: 'He runs quickly.'", "o": ["He", "runs", "quickly", "fast"], "a": "quickly"},
            {"q": "24. Preposition: 'The cat is under the table.'", "o": ["The", "cat", "is", "under"], "a": "under"},
            {"q": "25. 'I like tea ___ I don't like coffee.'", "o": ["and", "but", "or", "so"], "a": "but"},
            {"q": "26. Compound noun:", "o": ["Football", "Play", "Beautiful", "Quickly"], "a": "Football"},
            {"q": "27. Correct sentence:", "o": ["She don't like fish.", "She doesn't likes fish.", "She doesn't like fish.", "She not like fish."], "a": "She doesn't like fish."},
            {"q": "28. Future sentence:", "o": ["I will go.", "I am going.", "I go.", "I went."], "a": "I will go."},
            {"q": "29. Past sentence:", "o": ["They played.", "They play.", "They will play.", "They are playing."], "a": "They played."},
            {"q": "30. Interjection:", "o": ["Wow!", "And", "Running", "Happy"], "a": "Wow!"}
        ],
        "7": [
            {"q": "1. If I ___ a lot of money, I would buy a car.", "o": ["have", "had", "has", "having"], "a": "had"},
            {"q": "2. She ___ since 2 o'clock.", "o": ["is waiting", "waits", "has been waiting", "waited"], "a": "has been waiting"},
            {"q": "3. The car ___ last week.", "o": ["repaired", "is repaired", "was repaired", "was repair"], "a": "was repaired"},
            {"q": "4. He said that he ___ a doctor.", "o": ["is", "was", "be", "been"], "a": "was"},
            {"q": "5. This is the man ___ son is a pilot.", "o": ["who", "which", "whose", "whom"], "a": "whose"},
            {"q": "6. I'm not used to ___ early.", "o": ["get up", "getting up", "got up", "gets up"], "a": "getting up"},
            {"q": "7. You ___ see a doctor.", "o": ["should", "ought", "must to", "shall"], "a": "should"},
            {"q": "8. By next year, I ___ my studies.", "o": ["finish", "will finish", "will have finished", "finished"], "a": "will have finished"},
            {"q": "9. It's time we ___.", "o": ["leave", "left", "leaving", "to leave"], "a": "left"},
            {"q": "10. I wish I ___ taller.", "o": ["am", "was", "were", "be"], "a": "were"},
            {"q": "11. 'Hospital' is a place where ___.", "o": ["we learn", "sick people go", "we play", "we buy food"], "a": "sick people go"},
            {"q": "12. 'Ancient' means ___.", "o": ["very old", "very new", "modern", "fast"], "a": "very old"},
            {"q": "13. 'Artificial' opposite is ___.", "o": ["fake", "natural", "man-made", "strong"], "a": "natural"},
            {"q": "14. 'Gradually' means ___.", "o": ["suddenly", "slowly over time", "quickly", "never"], "a": "slowly over time"},
            {"q": "15. 'Evidence' means ___.", "o": ["proof", "a story", "a lie", "a question"], "a": "proof"},
            {"q": "16. 'Wealthy' means ___.", "o": ["poor", "rich", "sick", "healthy"], "a": "rich"},
            {"q": "17. 'Benefit' means ___.", "o": ["advantage", "problem", "danger", "cost"], "a": "advantage"},
            {"q": "18. 'Drought' is a period with no ___.", "o": ["food", "rain", "sun", "wind"], "a": "rain"},
            {"q": "19. 'Occur' means ___.", "o": ["to happen", "to finish", "to start", "to stop"], "a": "to happen"},
            {"q": "20. 'Essential' means ___.", "o": ["not important", "necessary", "extra", "cheap"], "a": "necessary"},
            {"q": "21. Gerund: 'Smoking is bad.'", "o": ["bad", "is", "Smoking", "Smoking is"], "a": "Smoking"},
            {"q": "22. Passive: 'Bread is made here.'", "o": ["Bread is", "is made", "made", "here"], "a": "is made"},
            {"q": "23. Conjunction: 'Although it was cold, we went out.'", "o": ["Although", "was", "cold", "out"], "a": "Although"},
            {"q": "24. Modal: 'You must study.'", "o": ["must", "study", "You", "You must"], "a": "must"},
            {"q": "25. Relative clause: 'The boy who is tall.'", "o": ["who", "is", "tall", "boy"], "a": "who"},
            {"q": "26. Compound adjective:", "o": ["Good-looking", "Happy", "Beautifully", "Run"], "a": "Good-looking"},
            {"q": "27. Conditional:", "o": ["If I win...", "I win.", "I will win.", "I won."], "a": "If I win..."},
            {"q": "28. Indirect speech:", "o": ["He said he was tired.", "He says tired.", "He said tired.", "He tired."], "a": "He said he was tired."},
            {"q": "29. Direct speech:", "o": ["'I am tired.'", "I am tired.", "He said I am tired.", "Tired I am."], "a": "'I am tired.'"},
            {"q": "30. Question tag: 'She is nice, ___?'", "o": ["isn't she", "is she", "doesn't she", "does she"], "a": "isn't she"}
        ],
        "8": [
            {"q": "1. I have ___ my keys.", "o": ["lose", "lost", "losing", "loses"], "a": "lost"},
            {"q": "2. She ___ French since she was 10.", "o": ["studied", "studies", "has been studying", "is studying"], "a": "has been studying"},
            {"q": "3. The cake ___ by my mother.", "o": ["was baked", "baked", "is bake", "bakes"], "a": "was baked"},
            {"q": "4. If I ___ you, I would go.", "o": ["am", "was", "were", "be"], "a": "were"},
            {"q": "5. He asked where ___.", "o": ["did I live", "I lived", "do I live", "I live"], "a": "I lived"},
            {"q": "6. I ___ like pizza, but now I do.", "o": ["used to", "didn't use to", "use to", "am used to"], "a": "didn't use to"},
            {"q": "7. By the time he came, we ___ dinner.", "o": ["finished", "have finished", "had finished", "finish"], "a": "had finished"},
            {"q": "8. This is the house ___ I was born.", "o": ["which", "where", "who", "when"], "a": "where"},
            {"q": "9. You ___ better go now.", "o": ["had", "would", "should", "must"], "a": "had"},
            {"q": "10. I'm looking forward to ___ you.", "o": ["see", "seeing", "saw", "seen"], "a": "seeing"},
            {"q": "11. Although it was raining, ___.", "o": ["we went out", "we stay home", "it is wet", "raining"], "a": "we went out"},
            {"q": "12. He is the person ___ car was stolen.", "o": ["who", "whom", "whose", "which"], "a": "whose"},
            {"q": "13. I wish I ___ a car.", "o": ["have", "had", "has", "having"], "a": "had"},
            {"q": "14. Neither tea ___ coffee is available.", "o": ["or", "nor", "and", "but"], "a": "nor"},
            {"q": "15. The movie was ___ than the book.", "o": ["good", "better", "best", "the best"], "a": "better"},
            {"q": "16. She speaks English ___.", "o": ["good", "well", "fluent", "slow"], "a": "well"},
            {"q": "17. ___ you finish your work yet?", "o": ["Do", "Did", "Have", "Has"], "a": "Have"},
            {"q": "18. It ___ since yesterday.", "o": ["is raining", "rains", "has been raining", "rained"], "a": "has been raining"},
            {"q": "19. If it rains, we ___ at home.", "o": ["stay", "will stay", "stayed", "would stay"], "a": "will stay"},
            {"q": "20. The windows ___ every week.", "o": ["clean", "are cleaned", "cleaned", "cleaning"], "a": "are cleaned"},
            {"q": "21. Vocabulary: 'Ancient' means:", "o": ["Modern", "New", "Old", "Fast"], "a": "Old"},
            {"q": "22. Vocabulary: 'Huge' means:", "o": ["Small", "Large", "Tiny", "Little"], "a": "Large"},
            {"q": "23. Vocabulary: 'Wealthy' means:", "o": ["Poor", "Rich", "Sick", "Sad"], "a": "Rich"},
            {"q": "24. Vocabulary: 'Hardly' means:", "o": ["Very much", "Barely", "Strongly", "Easily"], "a": "Barely"},
            {"q": "25. Identify the noun: 'The teacher is kind.'", "o": ["teacher", "is", "kind", "the"], "a": "teacher"},
            {"q": "26. Correct sentence:", "o": ["I have went.", "I have gone.", "I gone.", "I have go."], "a": "I have gone."},
            {"q": "27. Modal: 'You ___ park here. It's forbidden.'", "o": ["mustn't", "shouldn't", "can't", "don't have to"], "a": "mustn't"},
            {"q": "28. Passive: 'The letter ___ written yesterday.'", "o": ["is", "was", "were", "be"], "a": "was"},
            {"q": "29. Tag: 'He is a student, ___?'", "o": ["is he", "isn't he", "does he", "doesn't he"], "a": "isn't he"},
            {"q": "30. Verb form: 'I am ___ a book.'", "o": ["read", "reading", "reads", "readed"], "a": "reading"}
        ],
        "9": [
            {"q": "1. By the time I arrived, the train ___.", "o": ["leaves", "has left", "had left", "left"], "a": "had left"},
            {"q": "2. Neither my mother ___ my father is here.", "o": ["or", "nor", "and", "but"], "a": "nor"},
            {"q": "3. I would have helped you if you ___ me.", "o": ["ask", "asked", "had asked", "have asked"], "a": "had asked"},
            {"q": "4. The room ___ every day.", "o": ["cleans", "is cleaned", "cleaned", "is cleaning"], "a": "is cleaned"},
            {"q": "5. I ___ my hair cut tomorrow.", "o": ["will have", "have", "am having", "will had"], "a": "will have"},
            {"q": "6. Despite ___ ill, she went to work.", "o": ["be", "being", "is", "was"], "a": "being"},
            {"q": "7. He works as ___ teacher.", "o": ["a", "an", "the", "no article"], "a": "a"},
            {"q": "8. This is the best film I ___ seen.", "o": ["ever", "never", "have ever", "had ever"], "a": "have ever"},
            {"q": "9. She ___ to be a doctor one day.", "o": ["hopes", "hope", "hoping", "hoped"], "a": "hopes"},
            {"q": "10. He suggested ___ to the park.", "o": ["go", "going", "to go", "goes"], "a": "going"},
            {"q": "11. 'Vast' means:", "o": ["Small", "Large", "Tiny", "Weak"], "a": "Large"},
            {"q": "12. 'Ancient' opposite is:", "o": ["Old", "Modern", "Classic", "History"], "a": "Modern"},
            {"q": "13. 'Artificial' means:", "o": ["Natural", "Fake", "Real", "Strong"], "a": "Fake"},
            {"q": "14. 'Gradually' means:", "o": ["Suddenly", "Slowly", "Quickly", "Never"], "a": "Slowly"},
            {"q": "15. 'Wealthy' means:", "o": ["Poor", "Rich", "Sick", "Sad"], "a": "Rich"},
            {"q": "16. 'Occur' means:", "o": ["Stop", "Start", "Happen", "Finish"], "a": "Happen"},
            {"q": "17. 'Essential' means:", "o": ["Not needed", "Necessary", "Extra", "Cheap"], "a": "Necessary"},
            {"q": "18. 'Drought' means no:", "o": ["Food", "Rain", "Sun", "Wind"], "a": "Rain"},
            {"q": "19. 'Benefit' means:", "o": ["Advantage", "Problem", "Danger", "Cost"], "a": "Advantage"},
            {"q": "20. 'Evidence' means:", "o": ["Story", "Proof", "Lie", "Joke"], "a": "Proof"},
            {"q": "21. She is looking forward to ___ her friend.", "o": ["meet", "meeting", "met", "meets"], "a": "meeting"},
            {"q": "22. If I were you, I ___ that.", "o": ["won't do", "wouldn't do", "don't do", "didn't do"], "a": "wouldn't do"},
            {"q": "23. The cake was ___ by her.", "o": ["make", "made", "making", "makes"], "a": "made"},
            {"q": "24. I have been working here ___ 2010.", "o": ["for", "since", "during", "at"], "a": "since"},
            {"q": "25. He works ___ than his brother.", "o": ["hard", "harder", "hardest", "more hard"], "a": "harder"},
            {"q": "26. I ___ go now, it's late.", "o": ["must", "can", "may", "might"], "a": "must"},
            {"q": "27. She is ___ girl in our class.", "o": ["tall", "taller", "the tallest", "more tall"], "a": "the tallest"},
            {"q": "28. Have you ___ finished?", "o": ["yet", "already", "still", "since"], "a": "already"},
            {"q": "29. Where ___ you yesterday?", "o": ["are", "was", "were", "is"], "a": "were"},
            {"q": "30. This is the house ___ I live.", "o": ["which", "who", "where", "when"], "a": "where"}
        ],
        "10": [
            {"q": "1. I am looking forward to ___ you.", "o": ["see", "seeing", "saw", "seen"], "a": "seeing"},
            {"q": "2. She ___ to be a doctor.", "o": ["wants", "wanting", "is want", "want"], "a": "wants"},
            {"q": "3. This is ___ film I've ever seen.", "o": ["the most interesting", "more interesting", "interesting", "interestinger"], "a": "the most interesting"},
            {"q": "4. If I had known, I ___ you.", "o": ["will tell", "would tell", "would have told", "told"], "a": "would have told"},
            {"q": "5. I ___ my homework by 8 PM tomorrow.", "o": ["will finish", "will have finished", "finished", "finish"], "a": "will have finished"},
            {"q": "6. He is used to ___ in a noisy office.", "o": ["work", "working", "works", "worked"], "a": "working"},
            {"q": "7. The more you study, the ___ you learn.", "o": ["much", "more", "most", "many"], "a": "more"},
            {"q": "8. I'd rather you ___ here.", "o": ["stay", "stayed", "staying", "to stay"], "a": "stayed"},
            {"q": "9. It's high time you ___ your bed.", "o": ["make", "made", "making", "to make"], "a": "made"},
            {"q": "10. Scarcely ___ I reached home when it started raining.", "o": ["did", "had", "have", "was"], "a": "had"},
            {"q": "11. 'Sustainable' means:", "o": ["Temporary", "Long-term", "Quick", "Weak"], "a": "Long-term"},
            {"q": "12. 'Consequence' means:", "o": ["Reason", "Result", "Beginning", "Cause"], "a": "Result"},
            {"q": "13. 'Implement' means:", "o": ["Stop", "Apply", "Plan", "Think"], "a": "Apply"},
            {"q": "14. 'Ambiguous' means:", "o": ["Clear", "Unclear", "Big", "Small"], "a": "Unclear"},
            {"q": "15. 'Obstacle' means:", "o": ["Help", "Barrier", "Road", "Door"], "a": "Barrier"},
            {"q": "16. 'Prioritize' means:", "o": ["Ignore", "Put first", "Last", "Forget"], "a": "Put first"},
            {"q": "17. 'Innovative' means:", "o": ["Old", "New/creative", "Boring", "Usual"], "a": "New/creative"},
            {"q": "18. 'Reliable' means:", "o": ["Trustworthy", "Fast", "Broken", "Cheap"], "a": "Trustworthy"},
            {"q": "19. 'Abundant' means:", "o": ["Small amount", "Plentiful", "Rare", "None"], "a": "Plentiful"},
            {"q": "20. 'Versatile' means:", "o": ["Fixed", "Multi-talented", "Limited", "Slow"], "a": "Multi-talented"},
            {"q": "21. She asked me where ___.", "o": ["was I", "I was", "am I", "is she"], "a": "I was"},
            {"q": "22. I can't help ___ when I see him.", "o": ["laugh", "laughing", "to laugh", "laughed"], "a": "laughing"},
            {"q": "23. He had his car ___ yesterday.", "o": ["repair", "repaired", "repairing", "repairs"], "a": "repaired"},
            {"q": "24. I wish I ___ more money.", "o": ["have", "had", "has", "having"], "a": "had"},
            {"q": "25. By next year, I ___ my degree.", "o": ["get", "will get", "will have got", "got"], "a": "will have got"},
            {"q": "26. Not only ___ he smart, but also kind.", "o": ["is", "does", "was", "has"], "a": "is"},
            {"q": "27. Provided that you ___ hard, you will pass.", "o": ["study", "studied", "will study", "studies"], "a": "study"},
            {"q": "28. You ___ better not tell him.", "o": ["had", "would", "should", "must"], "a": "had"},
            {"q": "29. He works ___ a doctor.", "o": ["as", "like", "for", "to"], "a": "as"},
            {"q": "30. ___ of the students passed.", "o": ["Neither", "Both", "Each", "All of these"], "a": "All of these"}
        ],
        "11": [
            {"q": "1. If I ___ you, I wouldn't do that.", "o": ["am", "was", "were", "be"], "a": "were"},
            {"q": "2. The homework ___ before the teacher checked it.", "o": ["has done", "had been done", "was done", "did"], "a": "had been done"},
            {"q": "3. By next month, I ___ for 5 years.", "o": ["will work", "will have been working", "work", "have worked"], "a": "will have been working"},
            {"q": "4. I would have helped you if you ___ me earlier.", "o": ["tell", "told", "had told", "telling"], "a": "had told"},
            {"q": "5. Not only ___ he study hard, but he also works.", "o": ["does", "is", "has", "do"], "a": "does"},
            {"q": "6. Suppose you ___ the lottery, what would you do?", "o": ["win", "won", "had won", "winning"], "a": "won"},
            {"q": "7. It is vital that he ___ on time.", "o": ["is", "be", "was", "been"], "a": "be"},
            {"q": "8. Having ___ the book, she went to sleep.", "o": ["read", "reading", "reads", "readed"], "a": "read"},
            {"q": "9. No sooner ___ she left than it rained.", "o": ["had", "did", "was", "has"], "a": "had"},
            {"q": "10. He works as if he ___ a machine.", "o": ["is", "was", "were", "be"], "a": "were"},
            {"q": "11. 'Inevitably' means:", "o": ["Avoidably", "Unavoidably", "Rarely", "Never"], "a": "Unavoidably"},
            {"q": "12. 'Controversial' means:", "o": ["Agreed", "Disputed", "Simple", "Old"], "a": "Disputed"},
            {"q": "13. 'Elaborate' means:", "o": ["Simple", "Detailed", "Small", "Weak"], "a": "Detailed"},
            {"q": "14. 'Significant' means:", "o": ["Minor", "Important", "Useless", "Small"], "a": "Important"},
            {"q": "15. 'Facilitate' means:", "o": ["Hinder", "Make easier", "Stop", "Break"], "a": "Make easier"},
            {"q": "16. 'Acquire' means:", "o": ["Lose", "Obtain/get", "Give", "Sell"], "a": "Obtain/get"},
            {"q": "17. 'Prevalent' means:", "o": ["Rare", "Common", "Unique", "New"], "a": "Common"},
            {"q": "18. 'Diminish' means:", "o": ["Increase", "Decrease", "Grow", "Stay"], "a": "Decrease"},
            {"q": "19. 'Pragmatic' means:", "o": ["Dreamy", "Practical", "Funny", "Angry"], "a": "Practical"},
            {"q": "20. 'Comprehensive' means:", "o": ["Partial", "Complete", "Short", "Limited"], "a": "Complete"},
            {"q": "21. She ___ TV when the lights went out.", "o": ["watched", "was watching", "has watched", "watches"], "a": "was watching"},
            {"q": "22. I would rather ___ at home.", "o": ["stay", "to stay", "staying", "stayed"], "a": "stay"},
            {"q": "23. He is said ___ the best student.", "o": ["is", "to be", "being", "was"], "a": "to be"},
            {"q": "24. There is no point in ___ him.", "o": ["ask", "asking", "to ask", "asked"], "a": "asking"},
            {"q": "25. By the time you arrive, I ___.", "o": ["leave", "will leave", "will have left", "left"], "a": "will have left"},
            {"q": "26. Hard as he tried, he ___ pass.", "o": ["didn't", "don't", "wasn't", "isn't"], "a": "didn't"},
            {"q": "27. Under no circumstances ___ you tell him.", "o": ["you should", "should you", "you must", "do you"], "a": "should you"},
            {"q": "28. I wish I ___ to the party yesterday.", "o": ["go", "went", "had gone", "going"], "a": "had gone"},
            {"q": "29. The book ___ by millions.", "o": ["reads", "is read", "read", "reading"], "a": "is read"},
            {"q": "30. You should ___ me the truth.", "o": ["tell", "have told", "told", "telling"], "a": "have told"}
        ]
    "Biologiya" : {
        "5": [
        {"q": "1. O'simliklar nima qiladi?", "o": ["Yuguradi", "Nafas oladi", "Fotosintez qiladi", "Uxlaydi"], "a": "Fotosintez qiladi"},
        {"q": "2. Hayvonlar nima qiladi?", "o": ["Faqat o'sadi", "Harakat qiladi", "Yonadi", "Muzlaydi"], "a": "Harakat qiladi"},
        {"q": "3. Odam nechta asosiy sezgi organiga ega?", "o": ["3", "4", "5", "6"], "a": "5"},
        {"q": "4. Ko'z nima uchun kerak?", "o": ["Eshitish", "Ko'rish", "Hid bilish", "Yurish"], "a": "Ko'rish"},
        {"q": "5. Quloq nima qiladi?", "o": ["Ko'radi", "Eshitadi", "Hidlash", "Ta'm sezadi"], "a": "Eshitadi"},
        {"q": "6. O'simliklar qaysi gazni yutadi?", "o": ["Kislorod", "Azot", "CO2", "Geliy"], "a": "CO2"},
        {"q": "7. O'simliklar qaysi gazni chiqaradi?", "o": ["CO2", "Kislorod", "Azot", "Vodorod"], "a": "Kislorod"},
        {"q": "8. Fotosintez qayerda bo'ladi?", "o": ["Ildiz", "Barg", "Poya", "Gul"], "a": "Barg"},
        {"q": "9. O'simliklar nima bilan oziqlanadi?", "o": ["Quyosh nuri", "Tuproq", "Plastik", "Yog'"], "a": "Quyosh nuri"},
        {"q": "10. Ildizning vazifasi?", "o": ["Gullash", "O'sish", "Suv olish", "Uchish"], "a": "Suv olish"},
        {"q": "11. Poya nima qiladi?", "o": ["O'ylaydi", "Tashiydi", "Yozadi", "Yutadi"], "a": "Tashiydi"},
        {"q": "12. Bargning asosiy vazifasi?", "o": ["Nafas olish va fotosintez", "Yurish", "Eshitish", "Ko'rish"], "a": "Nafas olish va fotosintez"},
        {"q": "13. Hayvonlar nafas oladi:", "o": ["Barg bilan", "O'pka yoki jabra bilan", "Ildiz bilan", "Teri bilan emas"], "a": "O'pka yoki jabra bilan"},
        {"q": "14. Baliqlar nima bilan nafas oladi?", "o": ["O'pka", "Jabralar", "Burun", "Teri"], "a": "Jabralar"},
        {"q": "15. Qushlar nima bilan qoplangan?", "o": ["Soch", "Jun", "Pat", "Tangacha"], "a": "Pat"},
        {"q": "16. Sut emizuvchilar nima bilan oziqlanadi?", "o": ["Sut bilan", "Suv bilan", "Tosh bilan", "Havo bilan"], "a": "Sut bilan"},
        {"q": "17. Odam organizmida eng katta organ?", "o": ["Yurak", "Teri", "Jigar", "O'pka"], "a": "Teri"},
        {"q": "18. Yurak nima qiladi?", "o": ["O'ylaydi", "Qonni haydaydi", "Nafas oladi", "Ko'radi"], "a": "Qonni haydaydi"},
        {"q": "19. Qon nima tashiydi?", "o": ["Faqat suv", "Kislorod va oziqa", "Faqat havo", "Yorug'lik"], "a": "Kislorod va oziqa"},
        {"q": "20. O'simliklar o'sishi uchun kerak emas:", "o": ["Suv", "Quyosh", "Kitob", "Tuproq"], "a": "Kitob"},
        {"q": "21. Tirik organizmlarning asosiy belgisi?", "o": ["O'sish", "Rang", "Shovqin", "Og'irlik"], "a": "O'sish"},
        {"q": "22. Mikroorganizmlar ko'rinadimi?", "o": ["Ha", "Yo'q", "Faqat kechasi", "Faqat suvda"], "a": "Yo'q"},
        {"q": "23. Bakteriyalar:", "o": ["Har doim zararli", "Faqat foydali", "Foydali va zararli", "Faqat o'lik"], "a": "Foydali va zararli"},
        {"q": "24. Zamburug'lar nima?", "o": ["Hayvon", "O'simlik", "Alohida organizm", "Tosh"], "a": "Alohida organizm"},
        {"q": "25. O'simlik hujayrasida nima bor?", "o": ["Xloroplast", "Tormoz", "Teri", "Qanot"], "a": "Xloroplast"},
        {"q": "26. Hujayra nima?", "o": ["Eng kichik tirik birlik", "Kiyim", "Ovqat", "Suv"], "a": "Eng kichik tirik birlik"},
        {"q": "27. DNK qayerda joylashgan?", "o": ["Hujayrada", "Havoda", "Suvda", "Toshda"], "a": "Hujayrada"},
        {"q": "28. Organlar birlashib nima hosil qiladi?", "o": ["Tizim", "Rang", "Ovoza", "O'yin"], "a": "Tizim"},
        {"q": "29. Nafas olish tizimi vazifasi?", "o": ["O'ylash", "Kislorod olish", "Yugurish", "Ko'rish"], "a": "Kislorod olish"},
        {"q": "30. Eng murakkab tirik organizm?", "o": ["O'simlik", "Hayvon", "Odam", "Bakteriya"], "a": "Odam"}
    ],
    "6": [
        {"q": "1. Tirik organizmlar nimani qiladi?", "o": ["Faqat o'sadi", "Nafas oladi", "Harakat qiladi", "Hammasi"], "a": "Hammasi"},
        {"q": "2. Hujayra nima?", "o": ["Eng kichik tirik birlik", "Organ", "To'qima", "Organizm"], "a": "Eng kichik tirik birlik"},
        {"q": "3. O'simliklar oziqa hosil qiladi:", "o": ["Nafas olish", "Fotosintez", "Ovqat hazm", "Filtrlash"], "a": "Fotosintez"},
        {"q": "4. Fotosintez qayerda bo'ladi?", "o": ["Yaproqda", "Ildizda", "Poyada", "G'urtda"], "a": "Yaproqda"},
        {"q": "5. Xlorofill vazifasi:", "o": ["Rang berish", "Yorug'likni yutish", "Suv ichish", "Harakat"], "a": "Yorug'likni yutish"},
        {"q": "6. Hayvon hujayrasida nima yo'q?", "o": ["Yadro", "Xloroplast", "Membrana", "Sitoplazma"], "a": "Xloroplast"},
        {"q": "7. O'simlik hujayrasida nima bor?", "o": ["Xloroplast", "Yurak", "Tish", "Miya"], "a": "Xloroplast"},
        {"q": "8. To'qima nima?", "o": ["Hujayralar guruhi", "Organ", "Organizm", "Teri"], "a": "Hujayralar guruhi"},
        {"q": "9. Organ nima?", "o": ["Hujayra", "To'qima", "Tizim qismi", "Atom"], "a": "Tizim qismi"},
        {"q": "10. Ildizning vazifasi?", "o": ["Fotosintez", "Suv va mineral olish", "Nafas olish", "Ko'rish"], "a": "Suv va mineral olish"},
        {"q": "11. Poya nima qiladi?", "o": ["O'ylaydi", "Moddalarni tashiydi", "Uxlaydi", "Yuguradi"], "a": "Moddalarni tashiydi"},
        {"q": "12. Barg nima qiladi?", "o": ["Faqat rang beradi", "Fotosintez", "Eshitish", "Yurish"], "a": "Fotosintez"},
        {"q": "13. O'simliklar nafas oladimi?", "o": ["Yo'q", "Ha", "Faqat kechasi", "Faqat suvda"], "a": "Ha"},
        {"q": "14. Hayvonlar energiyani qayerdan oladi?", "o": ["Quyosh", "Oziqa", "Tuproq", "Havo"], "a": "Oziqa"},
        {"q": "15. Oziq zanjiri nima?", "o": ["Ranglar", "Kim kimni yeydi", "Suv aylanishi", "Havo"], "a": "Kim kimni yeydi"},
        {"q": "16. Produsentlar kim?", "o": ["Hayvonlar", "O'simliklar", "Bakteriyalar", "Qo'ziqorinlar"], "a": "O'simliklar"},
        {"q": "17. Konsumentlar kim?", "o": ["O'simliklar", "Hayvonlar", "Toshlar", "Suv"], "a": "Hayvonlar"},
        {"q": "18. Redutsentlar vazifasi:", "o": ["O'sadi", "Parchalaydi", "Harakat", "Yorug'lik"], "a": "Parchalaydi"},
        {"q": "19. Ekotizim nima?", "o": ["Faqat o'rmon", "Tirik va jonsiz tabiat birligi", "Hayvon", "Suv"], "a": "Tirik va jonsiz tabiat birligi"},
        {"q": "20. Bakteriyalar:", "o": ["Faqat zararli", "Faqat foydali", "Har xil bo'ladi", "O'lik"], "a": "Har xil bo'ladi"},
        {"q": "21. Viruslar:", "o": ["Tirik emas", "O'simlik", "Hayvon", "Tuproq"], "a": "Tirik emas"},
        {"q": "22. Zamburug'lar:", "o": ["O'simlik emas", "Hayvon", "Tosh", "Metall"], "a": "O'simlik emas"},
        {"q": "23. Hujayra qobig'i vazifasi?", "o": ["Himoya", "Ovqat hazm", "Nafas", "Ko'rish"], "a": "Himoya"},
        {"q": "24. Sitoplazma nima?", "o": ["Hujayra ichidagi suyuqlik", "Tashqi qobiq", "Ildiz", "Poya"], "a": "Hujayra ichidagi suyuqlik"},
        {"q": "25. Yadro nima qiladi?", "o": ["Harakat", "Boshqaradi", "Rang beradi", "Nafas oladi"], "a": "Boshqaradi"},
        {"q": "26. O'simliklar qaysi gazni chiqaradi?", "o": ["CO2", "O2", "Azot", "Geliy"], "a": "O2"},
        {"q": "27. Hayvonlar qaysi gazni chiqaradi?", "o": ["Kislorod", "CO2", "Ozon", "Vodorod"], "a": "CO2"},
        {"q": "28. Moddalar almashinuvi nima?", "o": ["Ovqat yeyish", "Kirish-chiqish jarayoni", "Uyqu", "Rang"], "a": "Kirish-chiqish jarayoni"},
        {"q": "29. Organizm tizimi nimadan tuzilgan?", "o": ["Organlardan", "Toshdan", "Suvdan", "Havodan"], "a": "Organlardan"},
        {"q": "30. Eng yuqori biologik daraja?", "o": ["Hujayra", "To'qima", "Organizm", "Tizim"], "a": "Organizm"}
    ],
    "7": [
        {"q": "1. Hujayra kashfiyotchisi:", "o": ["Darwin", "Hooke", "Newton", "Mendel"], "a": "Hooke"},
        {"q": "2. Tirik organizm eng kichik birligi:", "o": ["To'qima", "Organ", "Hujayra", "Tizim"], "a": "Hujayra"},
        {"q": "3. O'simlik hujayrasida bor:", "o": ["Xloroplast", "Mitoxondriya", "Yadro", "Barchasi"], "a": "Barchasi"},
        {"q": "4. Hayvon hujayrasida yo'q:", "o": ["Yadro", "Xloroplast", "Membrana", "Sitoplazma"], "a": "Xloroplast"},
        {"q": "5. Hujayra membranasi vazifasi:", "o": ["Oziqa tayyorlash", "Himoya va nazorat", "Harakat", "Nafas"], "a": "Himoya va nazorat"},
        {"q": "6. Mitoxondriya vazifasi:", "o": ["Oziqa", "Energiya hosil qilish", "Ko'payish", "Himoya"], "a": "Energiya hosil qilish"},
        {"q": "7. Fotosintez qayerda bo'ladi?", "o": ["Yadro", "Xloroplast", "Mitoxondriya", "Ribosoma"], "a": "Xloroplast"},
        {"q": "8. O'simliklar qanday organizm?", "o": ["Geterotrof", "Avtotrof", "Parazit", "Yirtqich"], "a": "Avtotrof"},
        {"q": "9. To'qima nima?", "o": ["Hujayralar guruhi", "Organlar", "Tizim", "Organizm"], "a": "Hujayralar guruhi"},
        {"q": "10. Organlar birlashib hosil qiladi:", "o": ["Tizim", "Hujayra", "To'qima", "DNK"], "a": "Tizim"},
        {"q": "11. Yurak qaysi tizimga kiradi?", "o": ["Nafas", "Qon aylanish", "Hazm", "Nerv"], "a": "Qon aylanish"},
        {"q": "12. Qon aylanish vazifasi:", "o": ["Oziqa tashish", "Harakat", "Nafas", "Himoya"], "a": "Oziqa tashish"},
        {"q": "13. O'pka tizimi:", "o": ["Nafas olish", "Hazm", "Nerv", "Qon"], "a": "Nafas olish"},
        {"q": "14. Oshqozon vazifasi:", "o": ["Qon haydash", "Ovqat hazm qilish", "Nafas", "Harakat"], "a": "Ovqat hazm qilish"},
        {"q": "15. Nerv tizimi boshqaradi:", "o": ["Faqat yurak", "Butun organizm", "Faqat nafas", "Faqat oshqozon"], "a": "Butun organizm"},
        {"q": "16. DNK nima?", "o": ["Oqsil", "Genetik axborot", "Suv", "Energiya"], "a": "Genetik axborot"},
        {"q": "17. Gen nima?", "o": ["Hujayra", "Irsiy belgi birligi", "Organ", "Tizim"], "a": "Irsiy belgi birligi"},
        {"q": "18. Mendel sohasi:", "o": ["Evolyutsiya", "Irsiyat qonunlari", "Fizika", "Kimyo"], "a": "Irsiyat qonunlari"},
        {"q": "19. Evolyutsiya asoschisi:", "o": ["Darwin", "Newton", "Hooke", "Pasteur"], "a": "Darwin"},
        {"q": "20. Tabiiy tanlanish:", "o": ["Tasodif", "Moslashganning yashashi", "O'lim", "Ko'payish"], "a": "Eng mos organizm yashab qolishi"},
        {"q": "21. Bakteriyalar:", "o": ["Ko'p hujayrali", "Bir hujayrali", "O'simlik", "Hayvon"], "a": "Bir hujayrali"},
        {"q": "22. Viruslar qanday?", "o": ["Tirik", "Hujayrasiz tuzilma", "O'simlik", "Hayvon"], "a": "Hujayrasiz tuzilma"},
        {"q": "23. Zamburug'lar oziqlanishi:", "o": ["Avtotrof", "Geterotrof", "Fotosintez", "Harakat"], "a": "Geterotrof"},
        {"q": "24. Ekotizim tarkibi:", "o": ["Hayvonlar", "Tirik va jonsiz muhit", "O'simlik", "Suv"], "a": "Tirik va jonsiz muhit"},
        {"q": "25. Produsentlar kimlar?", "o": ["Hayvonlar", "O'simliklar", "Zamburug'lar", "Bakteriyalar"], "a": "O'simliklar"},
        {"q": "26. Konsumentlar kimlar?", "o": ["O'simliklar", "Hayvonlar", "Suv", "Tuproq"], "a": "Hayvonlar"},
        {"q": "27. Redutsentlar vazifasi:", "o": ["O'sadi", "Chiritadi", "Nafas", "Harakat"], "a": "Chiritadi"},
        {"q": "28. Oziq zanjiri nima?", "o": ["Tasodif", "Energiya oqimi", "Havo", "Suv"], "a": "Energiya oqimi"},
        {"q": "29. Eng yuqori trofik daraja:", "o": ["O'simlik", "Yirtqich", "Bakteriya", "Suv"], "a": "Yirtqich"},
        {"q": "30. Biologiya nima o'rganadi?", "o": ["Toshlarni", "Tirik organizmlarni", "Faqat odamni", "O'simlikni"], "a": "Tirik organizmlarni"}
    ],
    "8": [
        {"q": "1. Hujayra nazariyasi asoschilari:", "o": ["Hooke va Schleiden", "Darwin va Newton", "Mendel va Pasteur", "Lamarck"], "a": "Hooke va Schleiden"},
        {"q": "2. DNK asosiy vazifasi:", "o": ["Energiya", "Irsiy axborot saqlash", "Hazm", "Harakat"], "a": "Irsiy axborotni saqlash"},
        {"q": "3. RNK vazifasi:", "o": ["Oqsil sintezi", "Suv tashish", "Himoya", "Harakat"], "a": "Oqsil sintezi"},
        {"q": "4. Ribosoma nima qiladi?", "o": ["Energiya", "Oqsil sintezi", "DNK saqlash", "Suv"], "a": "Oqsil sintez qiladi"},
        {"q": "5. Mitoxondriya vazifasi:", "o": ["Fotosintez", "Energiya (ATP)", "Oqartirish", "Himoya"], "a": "Energiya (ATP) hosil qilish"},
        {"q": "6. Xloroplast qayerda?", "o": ["Hayvon", "O'simlik", "Bakteriya", "Virus"], "a": "O'simliklarda"},
        {"q": "7. Prokaryotda nima yo'q?", "o": ["Membrana", "Yadro", "Sitoplazma", "Ribosoma"], "a": "Yadro"},
        {"q": "8. Eukaryot hujayra nima?", "o": ["Yadrosiz", "Yadroga ega", "Bakteriya", "Virus"], "a": "Yadroga ega"},
        {"q": "9. Gen nima?", "o": ["Oqsil", "Irsiyat birligi", "Energiya", "To'qima"], "a": "Irsiyat birligi"},
        {"q": "10. Allel nima?", "o": ["Gen varianti", "Hujayra turi", "Organ", "Tizim"], "a": "Gen varianti"},
        {"q": "11. Dominant belgi:", "o": ["Yo'qoladi", "Namoyon bo'ladi", "Yashirin", "Yo'q"], "a": "Namoyon bo'ladi"},
        {"q": "12. Recessiv belgi:", "o": ["Har doim ko'rinadi", "Yashirin qoladi", "Organ", "Oqsil"], "a": "Yashirin qolishi mumkin"},
        {"q": "13. Mendel tajribasi ob'ekti:", "o": ["No'xat", "Mushuk", "Baliq", "Odam"], "a": "No'xat o'simligi"},
        {"q": "14. Genotip nima?", "o": ["Ko'rinish", "Genlar yig'indisi", "Rang", "Og'irlik"], "a": "Genlar yig'indisi"},
        {"q": "15. Fenotip nima?", "o": ["Genlar", "Tashqi belgi", "DNK", "Yadro"], "a": "Tashqi belgi"},
        {"q": "16. Ekotizim tarkibi:", "o": ["O'simlik", "Tirik va jonsiz", "Hayvon", "Suv"], "a": "Tirik va jonsiz muhit"},
        {"q": "17. Produsentlar:", "o": ["Hayvonlar", "O'simliklar", "Yirtqichlar", "Odam"], "a": "O'simliklar"},
        {"q": "18. Konsumentlar:", "o": ["O'simliklar", "Hayvonlar", "Zamburug'", "Bakteriya"], "a": "Hayvonlar"},
        {"q": "19. Redutsentlar vazifasi:", "o": ["O'sadi", "Chiritadi", "Harakat", "Nafas"], "a": "Chiritadi"},
        {"q": "20. Oziq zanjiri boshlanadi:", "o": ["Yirtqich", "Produsent", "Odam", "Suv"], "a": "Produsentdan"},
        {"q": "21. Energiya oqimi yo'nalishi:", "o": ["Aylana", "Bir yo'nalish", "Yo'qoladi", "To'xtaydi"], "a": "Bir yo'nalishda"},
        {"q": "22. Biotsenoz nima?", "o": ["Tiriklar jamlanmasi", "Suv", "Tuproq", "Havo"], "a": "Tirik organizmlar jamlanmasi"},
        {"q": "23. Biotop nima?", "o": ["Tiriklar", "Jonsiz muhit", "O'simlik", "Hayvon"], "a": "Jonsiz muhit"},
        {"q": "24. Populyatsiya:", "o": ["Bir tur guruhi", "Turli hayvon", "O'simlik", "Tuproq"], "a": "Bir tur individlari guruhi"},
        {"q": "25. Adaptatsiya nima?", "o": ["O'lish", "Moslashish", "O'sish", "Parchalash"], "a": "Moslashish"},
        {"q": "26. Evolyutsiya natijasi:", "o": ["Tasodif", "Turlar o'zgarishi", "Suv", "Havo"], "a": "Turlar o'zgarishi"},
        {"q": "27. Tabiiy tanlanishda:", "o": ["Zaif yashaydi", "Eng mos yashaydi", "Hamma o'ladi", "Tasodif"], "a": "Eng mos yashaydi"},
        {"q": "28. Viruslar nima?", "o": ["Hujayra", "Hujayrasiz tuzilma", "O'simlik", "Hayvon"], "a": "Hujayrasiz tuzilma"},
        {"q": "29. Immunitet vazifasi:", "o": ["Hazm", "Himoya", "Harakat", "Nafas"], "a": "Himoya"},
        {"q": "30. Biologiya o'rganadi:", "o": ["Odamni", "Tirik organizmlar hayotini", "Toshni", "Suvni"], "a": "Tirik organizmlar va ularning hayotini"}
    ],
    "9": [
        {"q": "1. Mitoz natijasi:", "o": ["2 ta bir xil hujayra", "4 hujayra", "1 hujayra", "yo'q"], "a": "2 ta bir xil hujayra"},
        {"q": "2. Meyoz natijasi:", "o": ["2 hujayra", "4 xil hujayra", "1 hujayra", "to'qima"], "a": "4 genetik turli hujayra"},
        {"q": "3. Replikatsiya qayerda?", "o": ["Ribosoma", "Yadro", "Mitoxondriya", "Membrana"], "a": "Yadro"},
        {"q": "4. Xromosoma nima?", "o": ["Oqsil", "DNK va oqsil", "Suv", "Yog"], "a": "DNK va oqsil kompleksi"},
        {"q": "5. Genetik kod xizmati:", "o": ["Energiya", "Oqsil sintezi", "Harakat", "Nafas"], "a": "Oqsil sintezi"},
        {"q": "6. Mendel 1-qonuni:", "o": ["Ajralish", "Bir xillik", "Moslashish", "Mutatsiya"], "a": "Bir xillik"},
        {"q": "7. Geterozigota:", "o": ["Bir xil", "Turli allellar", "O'lik", "Bakteriya"], "a": "Turli allellar"},
        {"q": "8. Gomozigota nima?", "o": ["AA yoki aa", "Aa", "DNK", "RNK"], "a": "AA yoki aa"},
        {"q": "9. Mutatsiya nima?", "o": ["O'sish", "DNK o'zgarishi", "Ovqatlanish", "Harakat"], "a": "DNK o'zgarishi"},
        {"q": "10. Mutatsiya sababi:", "o": ["Radiatsiya", "Suv", "Oziqa", "Kislorod"], "a": "Radiatsiya"},
        {"q": "11. Evolyutsiya omili:", "o": ["Tasodif", "Tabiiy tanlanish", "Uyqu", "O'sish"], "a": "Tabiiy tanlanish"},
        {"q": "12. Tanlanishda yashaydi:", "o": ["Kuchli", "Eng moslashgan", "Katta", "Tez"], "a": "Eng moslashgan"},
        {"q": "13. Moslashuv jarayoni:", "o": ["Adaptatsiya", "Replikatsiya", "Difuziya", "Fotosintez"], "a": "Adaptatsiya"},
        {"q": "14. Ekologik piramida:", "o": ["Genlar", "Energiya oqimi", "DNK", "Hujayra"], "a": "Energiya oqimi"},
        {"q": "15. Produsentlar kim?", "o": ["Hayvon", "O'simlik", "Zamburug", "Virus"], "a": "O'simliklar"},
        {"q": "16. Konsumentlar kim?", "o": ["O'simlik", "Hayvon", "Tuproq", "Suv"], "a": "Hayvon"},
        {"q": "17. Redutsentlar vazifasi:", "o": ["O'sish", "Chiritish", "Harakat", "Ko'payish"], "a": "Chiritadi"},
        {"q": "18. Zanjir boshlanishi:", "o": ["Yirtqich", "Produsent", "Parazit", "Virus"], "a": "Produsent"},
        {"q": "19. Ekotizim buzilishi:", "o": ["Barqarorlik", "Muvozanat buzilishi", "O'sish", "Ko'payish"], "a": "Muvozanat buzilishi"},
        {"q": "20. Biotsenoz nima?", "o": ["Muhit", "Tiriklar jamlanmasi", "Suv", "Tuproq"], "a": "Tirik organizmlar jamlanmasi"},
        {"q": "21. Biotop nima?", "o": ["Tirik", "Jonsiz muhit", "Gen", "Oqsil"], "a": "Jonsiz muhit"},
        {"q": "22. Populyatsiya nima?", "o": ["Bir tur individlar", "Turlar", "O'simlik", "Virus"], "a": "Bir tur individlar"},
        {"q": "23. Tur mezoni:", "o": ["Rang", "O'zaro ko'payish", "Hajm", "Og'irlik"], "a": "O'zaro ko'payish"},
        {"q": "24. Klassifikatsiya asoschisi:", "o": ["Darwin", "Linney", "Mendel", "Newton"], "a": "Linney"},
        {"q": "25. Viruslar qanday?", "o": ["Tirik hujayra", "Hujayrasiz", "O'simlik", "Hayvon"], "a": "Hujayrasiz"},
        {"q": "26. Immunitet nima?", "o": ["Hazm", "Himoya", "Harakat", "O'sish"], "a": "Himoya"},
        {"q": "27. Antitanacha vazifasi:", "o": ["Energiya", "Yo'q qilish", "DNK", "Suv"], "a": "Patogenlarni yo'q qilish"},
        {"q": "28. Qon tarkibi:", "o": ["Plazma", "Plazma va hujayralar", "Hujayra", "Yog"], "a": "Plazma va hujayralar"},
        {"q": "29. Nafas olish mahsuloti:", "o": ["ATP", "Oziqa", "DNK", "Suv"], "a": "ATP"},
        {"q": "30. Biologiya o'rganadi:", "o": ["Odam", "Tirik organizmlar", "Tosh", "Suv"], "a": "Tirik organizmlar va hayot jarayonlari"}
    ],
    "10": [
        {"q": "1. ATP nima?", "o": ["Oqsil", "Energiya molekulasi", "DNK", "Yog"], "a": "Energiya tashuvchi molekula"},
        {"q": "2. Glyukoza parchalanishi:", "o": ["Mitoxondriya", "Sitoplazma", "Yadro", "Ribosoma"], "a": "Sitoplazma"},
        {"q": "3. Anaerobda kislorod:", "o": ["Kerak", "Kerak emas", "Zararli", "Oqsil"], "a": "Kerak emas"},
        {"q": "4. Aerob mahsuloti:", "o": ["Sut kislota", "ATP, CO2, H2O", "DNK", "Glikogen"], "a": "ATP, CO2, H2O"},
        {"q": "5. Fotosintez gazi:", "o": ["O2", "CO2", "N2", "H2"], "a": "CO2"},
        {"q": "6. Xlorofill joylashishi:", "o": ["Yadro", "Xloroplast", "Ribosoma", "Membrana"], "a": "Xloroplast"},
        {"q": "7. Fermentlar nima?", "o": ["Yog", "Katalizatorlar", "DNK", "Tuz"], "a": "Biologik katalizatorlar"},
        {"q": "8. Ferment ishlashi:", "o": ["Harorat va pH", "Yorug'lik", "Tuz", "Shovqin"], "a": "Harorat va pH mos bo'lishi"},
        {"q": "9. DNK asoslari:", "o": ["A, T, G, C", "A, U, G, C", "A, B, C, D", "1,2,3"], "a": "A, T, G, C"},
        {"q": "10. RNKda T o'rniga:", "o": ["A", "U", "G", "C"], "a": "U"},
        {"q": "11. Transkripsiya:", "o": ["DNK -> RNK", "RNK -> DNK", "Oqsil", "Yog"], "a": "DNK → RNK"},
        {"q": "12. Translatsiya qayerda?", "o": ["Yadro", "Ribosoma", "Mitoxondriya", "Xloroplast"], "a": "Ribosoma"},
        {"q": "13. Genetik kod nima?", "o": ["Rang", "Kod tizimi", "Suv", "Energiya"], "a": "Aminokislotalar kod tizimi"},
        {"q": "14. Mutatsiya nima?", "o": ["Bo'linish", "DNK o'zgarishi", "Harakat", "Nafas"], "a": "DNK o'zgarishi"},
        {"q": "15. Mutatsiya tabiati:", "o": ["Foydali", "Zararli", "Tasodifiy", "Ko'rinmas"], "a": "Tasodifiy"},
        {"q": "16. Mejoz natijasi:", "o": ["2 hujayra", "4 gameta", "1 hujayra", "yo'q"], "a": "4 gameta"},
        {"q": "17. Crossing-over nima?", "o": ["DNK almashinuvi", "Hazm", "Nafas", "Suv"], "a": "DNK almashinuvi"},
        {"q": "18. Genotip nima?", "o": ["Ko'rinish", "Genlar yig'indisi", "Rang", "Og'irlik"], "a": "Genlar yig'indisi"},
        {"q": "19. Fenotip nima?", "o": ["Genlar", "Tashqi belgi", "Yadro", "DNK"], "a": "Tashqi belgi"},
        {"q": "20. Tabiiy tanlanish:", "o": ["Tasodif", "Mos yashab qolish", "O'lim", "O'sish"], "a": "Eng mos yashab qolish"},
        {"q": "21. Evolyutsiya nima?", "o": ["O'zgarish", "Muzlash", "Yo'qolish", "To'xtash"], "a": "O'zgarish"},
        {"q": "22. Populyatsiya nima?", "o": ["Bir tur guruhi", "Turlar", "Suv", "Tuproq"], "a": "Bir tur guruhi"},
        {"q": "23. Hardy-Weinberg:", "o": ["Barqaror holat", "Oziq zanjiri", "Nafas", "Fotosintez"], "a": "Evolyutsiya to'xtagan holat"},
        {"q": "24. Piramida asosi:", "o": ["DNK", "Energiya oqimi", "Oqsil", "Tuz"], "a": "Energiya oqimi"},
        {"q": "25. Energiya oqimi:", "o": ["Aylana", "Bir yo'nalish", "Tasodif", "Yo'q"], "a": "Bir yo'nalish"},
        {"q": "26. Reduksentlar:", "o": ["O'sish", "Chiritish", "Nafas", "Ko'payish"], "a": "Chiritadi"},
        {"q": "27. Biotsenoz nima?", "o": ["Tiriklar", "Suv", "Havo", "Tuproq"], "a": "Tiriklar jamlanmasi"},
        {"q": "28. Biotop nima?", "o": ["Tirik muhit", "Jonsiz muhit", "DNK", "Hujayra"], "a": "Jonsiz muhit"},
        {"q": "29. Viruslar nima?", "o": ["Hujayra", "Hujayrasiz", "O'simlik", "Bakteriya"], "a": "Hujayrasiz"},
        {"q": "30. Biologiya o'rganadi:", "o": ["Odam", "Tirik organizmlar", "Tosh", "Suv"], "a": "Tirik organizmlar va jarayonlar"}
    ],
    "11": [
        {"q": "1. Replikatsiya natijasi:", "o": ["1 DNK", "2 bir xil DNK", "RNK", "oqsil"], "a": "2 bir xil DNK"},
        {"q": "2. DNK polimeraza vazifasi:", "o": ["Parchalash", "Sintez qilish", "ATP", "Yemirish"], "a": "DNK sintez qiladi"},
        {"q": "3. Transkripsiya joyi:", "o": ["Ribosoma", "Yadro", "Mitoxondriya", "Golji"], "a": "Yadro"},
        {"q": "4. Translatsiya nima?", "o": ["DNK nusxa", "RNKdan oqsil", "Yog'", "Bo'linish"], "a": "RNKdan oqsil sintezi"},
        {"q": "5. Kodon nima?", "o": ["DNK bo'lagi", "RNK 3 nukleotid", "oqsil", "ferment"], "a": "RNKdagi 3 ta nukleotid"},
        {"q": "6. Antikodon qayerda?", "o": ["tRNK", "DNK", "mRNK", "ATP"], "a": "tRNK"},
        {"q": "7. Genetik kod xususiyati:", "o": ["Tasodif", "Universal", "O'zgaruvchan", "Odamniki"], "a": "universal"},
        {"q": "8. Mutatsiya nima?", "o": ["Foydali", "DNK o'zgarishi", "O'lim", "Oziqlanish"], "a": "DNK o'zgarishi"},
        {"q": "9. Missens mutatsiya:", "o": ["O'zgarishsiz", "Aminokislota o'zgarishi", "DNK yo'qolishi", "Ko'payish"], "a": "aminokislota o'zgaradi"},
        {"q": "10. Nonsens mutatsiya:", "o": ["Stop-kodon", "DNK ko'payishi", "Oqsil kuchayishi", "Fotosintez"], "a": "stop-kodon paydo bo'ladi"},
        {"q": "11. Mejoz natijasi:", "o": ["2 hujayra", "4 gameta", "1 hujayra", "yo'q"], "a": "4 gameta"},
        {"q": "12. Crossing-over nima?", "o": ["Parchalanish", "Xromosoma almashishi", "Oqsil", "Mitoz"], "a": "xromosoma bo'lak almashishi"},
        {"q": "13. Mitoz natijasi:", "o": ["Turli xil", "Bir xil hujayralar", "Gameta", "Virus"], "a": "bir xil hujayralar"},
        {"q": "14. Allel nima?", "o": ["Gen varianti", "Oqsil", "Hujayra", "Organ"], "a": "gen varianti"},
        {"q": "15. Geterozigota:", "o": ["AA", "Aa", "aa", "AABB"], "a": "Aa"},
        {"q": "16. Genotip nima?", "o": ["Tashqi belgi", "Genlar yig'indisi", "Rang", "Vazn"], "a": "genlar yig'indisi"},
        {"q": "17. Fenotip nima?", "o": ["DNK", "Tashqi ko'rinish", "RNK", "Xromosoma"], "a": "tashqi ko'rinish"},
        {"q": "18. Hardy-Weinberg:", "o": ["Tezlashish", "Barqaror populyatsiya", "O'lim", "Mutatsiyasiz"], "a": "populyatsiya barqaror"},
        {"q": "19. Tabiiy tanlanish:", "o": ["Tasodif", "Moslashganlar", "Hamma", "Gen yo'qolishi"], "a": "moslashganlar yashaydi"},
        {"q": "20. Adaptatsiya nima?", "o": ["Moslashish", "O'lish", "Bo'linish", "Nafas"], "a": "moslashish"},
        {"q": "21. Ekotizim tarkibi:", "o": ["Tiriklar", "Tirik + jonsiz", "Suv", "O'simlik"], "a": "tirik + jonsiz muhit"},
        {"q": "22. Energiya oqimi:", "o": ["Aylana", "Bir yo'nalish", "Yo'qoladi", "Tasodif"], "a": "bir yo'nalish"},
        {"q": "23. Produsentlar kim?", "o": ["Hayvon", "O'simlik", "Zamburug", "Virus"], "a": "O'simliklar"},
        {"q": "24. Konsumentlar kim?", "o": ["O'simlik", "Hayvon", "Bakteriya", "Suv"], "a": "hayvon"},
        {"q": "25. Redutsentlar vazifasi:", "o": ["Ishlab chiqarish", "Parchalash", "Ko'payish", "Yutish"], "a": "parchalaydi"},
        {"q": "26. ATP asosan qayerda?", "o": ["Ribosoma", "Mitoxondriya", "Yadro", "Membrana"], "a": "mitoxondriya"},
        {"q": "27. Aerob nafas olish:", "o": ["Kislorodsiz", "Kislorodli", "O'simlik", "Bakteriya"], "a": "kislorodli"},
        {"q": "28. Fotosintez mahsuloti:", "o": ["CO2", "Glyukoza va O2", "Suv", "ATP yo'q"], "a": "glyukoza va O2"},
        {"q": "29. Biotexnologiya nima?", "o": ["Hayvonlar", "Biologik jarayonlar", "Fizika", "Kimyo"], "a": "biologik jarayonlardan foydalanish"},
        {"q": "30. Biologiya nima?", "o": ["Toshlar", "Tirik organizmlar", "Fizika", "Odam"], "a": "tirik organizmlar va ularning jarayonlari"}
        ]
    }
}
